### ISSUE TITLE
Does not recognize VS2022

### ISSUE THREAD

**Issue by jeffrson** [mscdex/buildcheck#2]
Build check throws an error 'Unable to detect compiler type' with Visual Studio 2022 installed.

msbuild.exe can be found on my system as
```
C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\MSBuild.exe
```
(that's on Windows 10 x64 - so it's not any longer located in "Program Files(x86)").

**Comment by jeffrson** [comment]
Looking at current master that's not true. Instead it appears to be cpu-features, that depends on buildcheck 0.0.3.

**Comment by jeffrson** [comment]
Now it fails for VS 17.4 indeed - under certain circumstances.

Apparently, Microsoft delivers Windows 10 SDK as package "Microsoft.VisualStudio.Component.Windows10SDK" without a version, but for Windows 11 there is "Microsoft.VisualStudio.Component.Windows11SDK.22000".

So if somebody (like me) uses Windows 10 and removes Windows 11 SDK, buildcheck fails to recognize the SDK and then it cannot detect compiler type.

Seems like algorithm is very fragile.

**Comment by altmind** [comment]
Can confirm, buildcheck cannot find VS2022 community edition

**Comment by mscdex** [comment]
Closing this as VS2022 support should be working and we now have CI verifying that as well.

**Comment by jeffrson** [comment]
Unfortunately this is not really true - even if CI is verifying (which prerequisites is it using?).

It still fails to detect VS2022 with only Windows 11 SDK (current default SDK 10.0.22000.0, as well as 10.0.22621.0). It only works if manually adding some Windows 10 SDK.

That's actually the same I described above. So nothing changed.

**Comment by mscdex** [comment]
I was under the impression that VS2022 detection was the problem, which is covered by the `windows-2022` Github Actions image.

For Windows 11 SDK detection, can you try applying this patch and see if that helps?:

```diff
diff --git a/lib/findvs.js b/lib/findvs.js
index ea87e14..d9794d7 100644
--- a/lib/findvs.js
+++ b/lib/findvs.js
@@ -156,8 +156,8 @@ function findModernVS() {
               const sdkVer = parseInt(m[2], 10);
               if (!isFinite(sdkVer) || sdkVer < 0)
                 continue;
-              fullVersion = `${sdk}.0.${sdkVer}.0`;
-              version = `${sdk}.0`;
+              fullVersion = `10.0.${sdkVer}.0`;
+              version = '10.0';
               break;
             }
           }
```

**Comment by jeffrson** [comment]
I'm sorry if it was misleading - the error message just says "Unable to detect compiler type".

And yes, this little patch helps indeed!

**Comment by mscdex** [comment]
Fixed in 19d7fbafb2642021bb2d5e3736218b9ceec56982. Thanks for the verification.
